---
driver:
  name: rackspace
  rackspace_username: <%= ENV['RACKSPACE_USERNAME'] %>
  rackspace_api_key: <%= ENV['RACKSPACE_API_KEY'] %>
  public_key_path: <%= ENV['RACKSPACE_PUBLIC_KEY'] %>
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[rackspace_support::default]
    attributes:
